# Данные и типы шкал

## Измерение и переменная

Что значит измерить что-либо? Это значит, **привести в соответствие исследуемому признаку какое-либо значение на шкале**.

Что может примером признака? Что угодно, что нам нужно измерить в рамках исследования: количество кружек кофе в день, уровень концентрации, количество ошибок, время реакции, степень выгорания, количество выполненных задач, уровень нейротизма, рейтинг студента, количество детей в семье, температура и т.д.

**Признак**, который мы исследуем, по-другому называется **переменной**. С этим понятием мы будем сталкиваться постоянно в анализе данных. По сути, если мы посмотрим на табличку наблюдений, то любой столбец с измерениям -- это переменная. По строкам располагаются наблюдения, например, каждый новый человек из нашей выборки.

Вернемся к кейсу с Никитой, которые изучает выгорание сотрудников ВУЗов. Сделаем табличку данных, которые мог намерить Никита.

```{r, eval=TRUE, message = FALSE}

teacher_number <- seq(1,30,1)
age <-  rep(c(27, 30, 32, 26, 27, 41),5)
exp <- rep(c("от 1 до 2", "от 1 до 2", "от 3 до 5", "от 3 до 5", "от 1 до 2", "больше 5"),5)
univer <-  rep(c("MSU", "HSE", "MSU", "RANEPA", "HSE", "RANEPA"),5)
burnout <- tibble(teacher_number, age, exp, univer)
kable(burnout[1:10,])
```
<!--kable(burnout) %>% scroll_box(width = "100%")-->

*Что здесь будет являться переменными?*

В определении измерения помимо признака есть второе важное понятие -- это шкала.

**Шкала** -- это система измерения. Для того, чтобы мы все могли пользоваться одинаковыми единицами измерениями и не сходили с ума, мы, люди планеты Земля, пользуемся едиными шкалами. Всего их 4, и они бывают **метрические и неметрические** -- то есть, можем ли мы приложить измерительную линейку к ним или нет. В качестве измерительной линейки здесь имеется в виду любой условный прибор, в котором есть цена деления (сантиметр, грамм, секунда, штука).

## Количественные и неколичественные данные

Данные, измеренные метрическими шкалами -- это **количественные** данные (например, рост, вес, число заболевших, температура. То, что нельзя измерить метрическими шкалами (например, цвет глаз, самочувствие, уровень нейротизма, уровень образования) -- это **неколичественные** данные, которые могут носить разные названия: **категориальные**, иногда **качественные**. 

<span style="color: grey;">Иногда данные называют качественными в противоположность количественным, но это не совсем верно: разделение на количественные и качественные обычно применяется по отношению к типам исследований, где качественные исследования -- это, например, интервью или анализ блоков текста. Но в результате этого анализа у нас вполне могут получиться количественные переменные, например, количество раз, которые употреблялось то или иное слово, поэтому по отношению к данным, а не типам исследований, я рекомендую не использовать слово "качественные". </span>

С количественными данными попроще -- это все, что можно измерить метрической шкалой, условной линейкой.

Среди неколичественных данных встречаются два типа: категориальные и ранговые (порядковые) 

Эти данные мы подробно рассмотрим на шкалах.

## Типы шкал

Как мы уже поняли, разные данные относятся к разным шкалам. 

Разные шкалы обладают разной **измерительной мощностью** -- точностью, с которой мы измеряем признак. Один и тот же признак можно измерить с разной точностью: например, в зависимости от исследовательского вопроса, рост может быть выражен количественно в сантиметрах на интервале {0; ∞}, а может быть закодирован в виде {"меньше 150 см"; 150 см и больше}, если нас интересует только преобладание над определенной чертой. 

Всего существуют 4 шкалы, если располагать их снизу вверх по измерительной мощности: наименований, порядковая, интервальная, отношений.

Шкала | Описание                                       | Возможные операции | Примеры              | 
------| -----------------------------------------------| ------------------ | -------------------- | 
**Отношений (абсолютная)** | Количественная, есть абсолютный ноль, можно посчитать и *на сколько* больше или меньше, и *во сколько раз* | =, $\neq$, >, <, +, -, ×, ÷ | Рост, вес, число заболевших | 
**Интервальная (разности)** | Количественная, но нет абсоолютного нуля, можно посчитать  *на сколько* больше или меньше, но нельзя посчитать, *во сколько раз* | =, $\neq$, >, <, +, - | Температура в градусах Цельсия, времяисчисление по разным календарям | 
**Порядковая (ранговая, ординальная)** | Качественная (категориальная), можно установить "больше" или "меньше", но нельзя посчитать количественно, на сколько больше или меньше | =, $\neq$, >, < | Уровень образования, уровень нейротизма, спортивный рейтинг | 
**Наименований (номинальная)** | Качественная (категориальная), нельзя установить "больше" или "меньше" | =, $\neq$ | Пол, цвет, место жительства, название университета | 



## Непрерывные и дискретные данные


